
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  L1EventPayload,
  loadContractArtifact,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  type Wallet,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import PublicGroupsContractArtifactJson from '../../target/publicgroups-PublicGroups.json' assert { type: 'json' };
export const PublicGroupsContractArtifact = loadContractArtifact(PublicGroupsContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract PublicGroups;
 */
export class PublicGroupsContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, PublicGroupsContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, PublicGroupsContract.artifact, wallet) as Promise<PublicGroupsContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<PublicGroupsContract>(Fr.ZERO, wallet, PublicGroupsContractArtifact, PublicGroupsContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeysHash(publicKeysHash: Fr, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<PublicGroupsContract>(publicKeysHash, wallet, PublicGroupsContractArtifact, PublicGroupsContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PublicGroupsContract['methods']>(
    opts: { publicKeysHash?: Fr; method?: M; wallet: Wallet },
    ...args: Parameters<PublicGroupsContract['methods'][M]>
  ) {
    return new DeployMethod<PublicGroupsContract>(
      opts.publicKeysHash ?? Fr.ZERO,
      opts.wallet,
      PublicGroupsContractArtifact,
      PublicGroupsContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PublicGroupsContractArtifact;
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'group_members' | 'group_balances' | 'member_count'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
group_members: {
      slot: new Fr(2n),
    },
group_balances: {
      slot: new Fr(3n),
    },
member_count: {
      slot: new Fr(4n),
    }
      } as ContractStorageLayout<'admin' | 'group_members' | 'group_balances' | 'member_count'>;
    }
    

  public static get notes(): ContractNotes<'AddressNote' | 'ValueNote'> {
    return {
      AddressNote: {
          id: new NoteSelector(1747431984),
        },
ValueNote: {
          id: new NoteSelector(1900156023),
        }
    } as ContractNotes<'AddressNote' | 'ValueNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_to_group(member: struct, approve: boolean) */
    add_to_group: ((member: AztecAddressLike, approve: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** admin() */
    admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** balance(creditor: struct, debtor: struct) */
    balance: ((creditor: AztecAddressLike, debtor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, serialized_note: array) */
    compute_note_hash_and_optionally_a_nullifier: ((contract_address: AztecAddressLike, nonce: FieldLike, storage_slot: FieldLike, note_type_id: FieldLike, compute_nullifier: boolean, serialized_note: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** in_group(group_member: struct) */
    in_group: ((group_member: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** make_payment(creditor: struct, debtor: struct, amount: integer) */
    make_payment: ((creditor: AztecAddressLike, debtor: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** member_count() */
    member_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** remove_from_group(member: struct, approve: boolean) */
    remove_from_group: ((member: AztecAddressLike, approve: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_balance(creditor: struct, debtor: struct, amount: field) */
    set_balance: ((creditor: AztecAddressLike, debtor: AztecAddressLike, amount: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** split_group_balance(creditor: struct, debtors: array, participants: integer, amount: integer) */
    split_group_balance: ((creditor: AztecAddressLike, debtors: AztecAddressLike[], participants: (bigint | number), amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
