"use strict";
/* Autogenerated file, do not edit! */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.PublicGroupsContract = exports.PublicGroupsContractArtifact = void 0;
/* eslint-disable */
var aztec_js_1 = require("@aztec/aztec.js");
var publicgroups_PublicGroups_json_1 = require("../../target/publicgroups-PublicGroups.json");
exports.PublicGroupsContractArtifact = (0, aztec_js_1.loadContractArtifact)(publicgroups_PublicGroups_json_1.default);
/**
 * Type-safe interface for contract PublicGroups;
 */
var PublicGroupsContract = /** @class */ (function (_super) {
    __extends(PublicGroupsContract, _super);
    function PublicGroupsContract(instance, wallet) {
        return _super.call(this, instance, exports.PublicGroupsContractArtifact, wallet) || this;
    }
    /**
     * Creates a contract instance.
     * @param address - The deployed contract's address.
     * @param wallet - The wallet to use when interacting with the contract.
     * @returns A promise that resolves to a new Contract instance.
     */
    PublicGroupsContract.at = function (address, wallet) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                return [2 /*return*/, aztec_js_1.Contract.at(address, PublicGroupsContract.artifact, wallet)];
            });
        });
    };
    /**
     * Creates a tx to deploy a new instance of this contract.
     */
    PublicGroupsContract.deploy = function (wallet, admin) {
        return new aztec_js_1.DeployMethod(aztec_js_1.Fr.ZERO, wallet, exports.PublicGroupsContractArtifact, PublicGroupsContract.at, Array.from(arguments).slice(1));
    };
    /**
     * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
     */
    PublicGroupsContract.deployWithPublicKeysHash = function (publicKeysHash, wallet, admin) {
        return new aztec_js_1.DeployMethod(publicKeysHash, wallet, exports.PublicGroupsContractArtifact, PublicGroupsContract.at, Array.from(arguments).slice(2));
    };
    /**
     * Creates a tx to deploy a new instance of this contract using the specified constructor method.
     */
    PublicGroupsContract.deployWithOpts = function (opts) {
        var _a, _b;
        var args = [];
        for (var _i = 1; _i < arguments.length; _i++) {
            args[_i - 1] = arguments[_i];
        }
        return new aztec_js_1.DeployMethod((_a = opts.publicKeysHash) !== null && _a !== void 0 ? _a : aztec_js_1.Fr.ZERO, opts.wallet, exports.PublicGroupsContractArtifact, PublicGroupsContract.at, Array.from(arguments).slice(1), (_b = opts.method) !== null && _b !== void 0 ? _b : 'constructor');
    };
    Object.defineProperty(PublicGroupsContract, "artifact", {
        /**
         * Returns this contract's artifact.
         */
        get: function () {
            return exports.PublicGroupsContractArtifact;
        },
        enumerable: false,
        configurable: true
    });
    Object.defineProperty(PublicGroupsContract, "storage", {
        get: function () {
            return {
                admin: {
                    slot: new aztec_js_1.Fr(1n),
                },
                group_members: {
                    slot: new aztec_js_1.Fr(2n),
                },
                group_balances: {
                    slot: new aztec_js_1.Fr(3n),
                }
            };
        },
        enumerable: false,
        configurable: true
    });
    Object.defineProperty(PublicGroupsContract, "notes", {
        get: function () {
            return {
                AddressNote: {
                    id: new aztec_js_1.NoteSelector(1747431984),
                },
                ValueNote: {
                    id: new aztec_js_1.NoteSelector(1900156023),
                }
            };
        },
        enumerable: false,
        configurable: true
    });
    return PublicGroupsContract;
}(aztec_js_1.ContractBase));
exports.PublicGroupsContract = PublicGroupsContract;
